node {
    stage('Terraform Deployment') {
        try {
            // TODO: Implement this.
            sh 'exit 1'
        }
        catch (exc) {
            echo 'EC2 deployment failed!'
            throw
        }
    }
}
